name: Upload to S3

on:
  push:
    branches: [master]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: npm install
      - name: Build apps
        run: npm run build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.IAM_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.IAM_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "./build"
          destination_dir: ""
